export interface Goal {
  id: string;
  title: string;
  icon: string;
  color: string;
  description: string;
  targetDate: string;
  status: 'active' | 'paused' | 'completed';
  milestones: Milestone[];
  streak: { current: number; longest: number };
}

export interface Milestone {
  id: string;
  title: string;
  completed: boolean;
  completedAt?: string;
}

export interface Task {
  id: string;
  title: string;
  icon: string;
  color: string;
  priority: 'urgent' | 'high' | 'medium' | 'low';
  dueDate: string;
  startTime?: string;
  endTime?: string;
  completed: boolean;
  recurring: boolean;
  recurrenceFrequency?: 'daily' | 'weekdays' | 'weekly' | 'monthly';
  goalId?: string;
  notes?: string;
}

export interface Workout {
  id: string;
  title: string;
  date: string;        // YYYY-MM-DD
  startTime?: string;  // HH:MM 24h
  durationMinutes: number;
  notes?: string;
  exercises: Exercise[];
  type: 'strength' | 'cardio' | 'flexibility' | 'sports';
  icon: string;
  programId?: string;  // set when generated by a WorkoutProgram
  completed?: boolean; // explicit completion flag (used by programs)
  skipped?: boolean;   // user chose to skip this session
  pushedFrom?: string; // original date before being pushed (YYYY-MM-DD)
}

/* ─── Workout Templates ─── */
export interface WorkoutTemplate {
  id: string;
  name: string;
  type: Workout['type'];
  icon: string;
  durationMinutes: number;
  exercises: Omit<Exercise, 'id'>[];
}

export const WORKOUT_TEMPLATES: WorkoutTemplate[] = [
  {
    id: 'tpl-1', name: 'Upper Body Strength',
    type: 'strength', icon: '💪', durationMinutes: 60,
    exercises: [
      { name: 'Bench Press',      sets: 4, reps: 8,  weightKg: 70   },
      { name: 'Pull-ups',         sets: 3, reps: 10                  },
      { name: 'Shoulder Press',   sets: 3, reps: 12, weightKg: 40   },
      { name: 'Cable Rows',       sets: 3, reps: 12, weightKg: 55   },
      { name: 'Tricep Pushdowns', sets: 3, reps: 15, weightKg: 30   },
    ],
  },
  {
    id: 'tpl-2', name: 'Lower Body Strength',
    type: 'strength', icon: '🦵', durationMinutes: 55,
    exercises: [
      { name: 'Back Squats',       sets: 4, reps: 10, weightKg: 80  },
      { name: 'Romanian Deadlift', sets: 3, reps: 12, weightKg: 65  },
      { name: 'Leg Press',         sets: 3, reps: 15, weightKg: 120 },
      { name: 'Walking Lunges',    sets: 3, reps: 20                 },
      { name: 'Calf Raises',       sets: 4, reps: 25                 },
    ],
  },
  {
    id: 'tpl-3', name: 'Full Body Strength',
    type: 'strength', icon: '🏋️', durationMinutes: 65,
    exercises: [
      { name: 'Deadlift',       sets: 4, reps: 5,  weightKg: 100 },
      { name: 'Bench Press',    sets: 3, reps: 8,  weightKg: 70  },
      { name: 'Back Squats',    sets: 3, reps: 8,  weightKg: 80  },
      { name: 'Pull-ups',       sets: 3, reps: 8                  },
      { name: 'Overhead Press', sets: 3, reps: 10, weightKg: 45  },
    ],
  },
  {
    id: 'tpl-4', name: 'Morning Run',
    type: 'cardio', icon: '🏃', durationMinutes: 40,
    exercises: [
      { name: 'Warm-up walk', durationSeconds: 300  },
      { name: 'Easy run',     durationSeconds: 1800 },
      { name: 'Cool-down',    durationSeconds: 300  },
    ],
  },
  {
    id: 'tpl-5', name: 'HIIT — Tabata',
    type: 'cardio', icon: '⚡', durationMinutes: 30,
    exercises: [
      { name: 'Burpees',           sets: 8, durationSeconds: 20 },
      { name: 'Mountain Climbers', sets: 8, durationSeconds: 20 },
      { name: 'Jump Squats',       sets: 8, durationSeconds: 20 },
      { name: 'High Knees',        sets: 8, durationSeconds: 20 },
    ],
  },
  {
    id: 'tpl-6', name: 'Morning Yoga',
    type: 'flexibility', icon: '🧘', durationMinutes: 30,
    exercises: [
      { name: 'Sun Salutations ×5', durationSeconds: 600 },
      { name: 'Warrior sequence',   durationSeconds: 480 },
      { name: 'Hip openers',        durationSeconds: 300 },
      { name: 'Savasana',           durationSeconds: 300 },
    ],
  },
  {
    id: 'tpl-7', name: 'Active Recovery',
    type: 'flexibility', icon: '🌿', durationMinutes: 30,
    exercises: [
      { name: 'Foam rolling',    durationSeconds: 600 },
      { name: 'Light stretching', durationSeconds: 900 },
      { name: 'Breathing work',  durationSeconds: 300 },
    ],
  },
];

/* ─── Workout Programs ─── */
export interface ProgramScheduleDay {
  id: string;
  dayLabel: string;    // "Day 1", "Day 2", …
  templateId: string;  // WorkoutTemplate.id
  startTime?: string;  // HH:MM
}

export interface WorkoutProgram {
  id: string;
  name: string;
  startDate: string;               // YYYY-MM-DD
  endDate: string;                 // YYYY-MM-DD
  schedule: ProgramScheduleDay[];
  generatedWorkoutIds: string[];
}

export interface Exercise {
  id: string;
  name: string;
  sets?: number;
  reps?: number;
  weightKg?: number;
  durationSeconds?: number;
}

/* ─── Ideas ─── */
export type IdeaCategory = 'personal' | 'work' | 'business' | 'creative' | 'health' | 'other';

export interface Idea {
  id: string;
  title: string;
  description?: string;
  icon: string;
  color: string;
  category: IdeaCategory;
  createdAt: string;       // ISO 8601
  convertedTo?: 'task' | 'goal';
  convertedId?: string;
}

export const mockIdeas: Idea[] = [
  {
    id: 'idea-1',
    title: 'Morning routine tracker',
    description: 'Build a simple tracker for my morning routine — meditation, exercise, journaling. Could be a widget on the home screen.',
    icon: '🌅',
    color: '#F5A524',
    category: 'personal',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'idea-2',
    title: 'Learn Spanish in 90 days',
    description: 'Duolingo + 30 min conversation practice daily. Target: hold a basic conversation by end of June.',
    icon: '🇪🇸',
    color: '#3EC99A',
    category: 'personal',
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'idea-3',
    title: 'Side project: Budget app',
    description: 'Simple income/expense tracker with visual charts. Mobile-first, can use this same tech stack as a starting point.',
    icon: '💰',
    color: '#7C6EF8',
    category: 'business',
    createdAt: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'idea-4',
    title: 'Podcast on productivity',
    description: 'Weekly 20-min episodes on systems and habits. Interview format + solo commentary.',
    icon: '🎙️',
    color: '#5BAFEF',
    category: 'creative',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockGoals: Goal[] = [
  {
    id: '1',
    title: 'Run a Marathon',
    icon: '🏃',
    color: '#7C6EF8',
    description: 'Complete my first full marathon by October. Training 4x per week.',
    targetDate: '2025-10-15',
    status: 'active',
    milestones: [
      { id: '1', title: 'Run 5K without stopping', completed: true, completedAt: '2025-03-01' },
      { id: '2', title: 'Complete first 10K race', completed: true, completedAt: '2025-03-20' },
      { id: '3', title: 'Half marathon training block', completed: false },
      { id: '4', title: 'Run 30K long run', completed: false },
      { id: '5', title: 'Race day! 🏁', completed: false },
    ],
    streak: { current: 12, longest: 18 },
  },
  {
    id: '2',
    title: 'Read 24 Books',
    icon: '📚',
    color: '#3EC99A',
    description: '2 books per month. Currently reading: Atomic Habits.',
    targetDate: '2025-12-31',
    status: 'active',
    milestones: [
      { id: '1', title: 'January ×2', completed: true, completedAt: '2025-01-31' },
      { id: '2', title: 'February ×2', completed: true, completedAt: '2025-02-28' },
      { id: '3', title: 'March ×2', completed: true, completedAt: '2025-03-31' },
      { id: '4', title: 'April ×2', completed: false },
      { id: '5', title: 'First half (12 books)', completed: false },
    ],
    streak: { current: 7, longest: 22 },
  },
  {
    id: '3',
    title: 'Launch LYFE App',
    icon: '🚀',
    color: '#FF7B72',
    description: 'Ship the personal life management app to production.',
    targetDate: '2025-05-30',
    status: 'active',
    milestones: [
      { id: '1', title: 'Define MVP features', completed: true, completedAt: '2025-04-01' },
      { id: '2', title: 'Build UI prototype', completed: false },
      { id: '3', title: 'Connect Supabase backend', completed: false },
      { id: '4', title: 'Beta testing round', completed: false },
      { id: '5', title: 'Launch! 🎉', completed: false },
    ],
    streak: { current: 3, longest: 8 },
  },
  {
    id: '4',
    title: 'Daily Meditation',
    icon: '🧘',
    color: '#F5A524',
    description: 'Build a consistent morning meditation practice — 10 min daily.',
    targetDate: '2025-12-31',
    status: 'active',
    milestones: [
      { id: '1', title: '7-day streak', completed: true, completedAt: '2025-03-15' },
      { id: '2', title: '21-day streak', completed: false },
      { id: '3', title: '100 sessions', completed: false },
    ],
    streak: { current: 21, longest: 21 },
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Morning meditation',
    icon: '🧘',
    color: '#F5A524',
    priority: 'high',
    dueDate: '2025-04-06',
    startTime: '07:00',
    endTime: '07:15',
    completed: true,
    recurring: true,
    goalId: '4',
  },
  {
    id: '2',
    title: 'Review LYFE requirements',
    icon: '📋',
    color: '#7C6EF8',
    priority: 'urgent',
    dueDate: '2025-04-06',
    startTime: '09:00',
    endTime: '10:00',
    completed: false,
    recurring: false,
    goalId: '3',
  },
  {
    id: '3',
    title: 'Lunch & walk',
    icon: '🥗',
    color: '#3EC99A',
    priority: 'medium',
    dueDate: '2025-04-06',
    startTime: '12:30',
    endTime: '13:15',
    completed: false,
    recurring: true,
  },
  {
    id: '4',
    title: 'Evening run — 8K',
    icon: '🏃',
    color: '#7C6EF8',
    priority: 'high',
    dueDate: '2025-04-06',
    startTime: '17:30',
    endTime: '18:30',
    completed: false,
    recurring: true,
    goalId: '1',
  },
  {
    id: '5',
    title: 'Read for 30 minutes',
    icon: '📚',
    color: '#3EC99A',
    priority: 'medium',
    dueDate: '2025-04-06',
    startTime: '20:00',
    endTime: '20:30',
    completed: false,
    recurring: true,
    goalId: '2',
  },
  {
    id: '6',
    title: 'Grocery shopping',
    icon: '🛒',
    color: '#FF7B72',
    priority: 'medium',
    dueDate: '2025-04-06',
    completed: false,
    recurring: false,
  },
  {
    id: '7',
    title: 'Call dentist',
    icon: '📞',
    color: '#5BAFEF',
    priority: 'low',
    dueDate: '2025-04-07',
    completed: false,
    recurring: false,
  },
  {
    id: '8',
    title: 'Weekly planning session',
    icon: '📅',
    color: '#7C6EF8',
    priority: 'high',
    dueDate: '2025-04-07',
    startTime: '10:00',
    endTime: '11:00',
    completed: false,
    recurring: true,
  },
  {
    id: '9',
    title: 'Upper body workout',
    icon: '💪',
    color: '#F97316',
    priority: 'high',
    dueDate: '2025-04-08',
    startTime: '07:00',
    endTime: '08:00',
    completed: false,
    recurring: false,
  },
  {
    id: '10',
    title: 'Design system review',
    icon: '🎨',
    color: '#F07FC6',
    priority: 'medium',
    dueDate: '2025-04-08',
    completed: false,
    recurring: false,
    goalId: '3',
  },
];

export const mockWorkouts: Workout[] = [
  {
    id: '1',
    title: 'Morning Run',
    date: '2025-04-06',
    durationMinutes: 45,
    type: 'cardio',
    icon: '🏃',
    notes: 'Easy 8K, felt strong throughout.',
    exercises: [
      { id: '1', name: 'Running — easy pace', durationSeconds: 2700 },
    ],
  },
  {
    id: '2',
    title: 'Upper Body Strength',
    date: '2025-04-05',
    durationMinutes: 60,
    type: 'strength',
    icon: '💪',
    exercises: [
      { id: '1', name: 'Bench Press',      sets: 4, reps: 8,  weightKg: 72.5 },
      { id: '2', name: 'Pull-ups',          sets: 3, reps: 10 },
      { id: '3', name: 'Shoulder Press',    sets: 3, reps: 12, weightKg: 42.5 },
      { id: '4', name: 'Cable Rows',        sets: 3, reps: 12, weightKg: 55   },
      { id: '5', name: 'Tricep Pushdowns',  sets: 3, reps: 15, weightKg: 30   },
    ],
  },
  {
    id: '3',
    title: 'Morning Yoga',
    date: '2025-04-04',
    durationMinutes: 30,
    type: 'flexibility',
    icon: '🧘',
    notes: 'Calm and restorative. Great way to start the day.',
    exercises: [
      { id: '1', name: 'Sun Salutations ×5', durationSeconds: 600 },
      { id: '2', name: 'Warrior sequence',   durationSeconds: 480 },
      { id: '3', name: 'Savasana',           durationSeconds: 300 },
    ],
  },
  {
    id: '4',
    title: 'Lower Body Strength',
    date: '2025-04-03',
    durationMinutes: 55,
    type: 'strength',
    icon: '🦵',
    exercises: [
      { id: '1', name: 'Back Squats',          sets: 4, reps: 10, weightKg: 82.5 },
      { id: '2', name: 'Romanian Deadlift',    sets: 3, reps: 12, weightKg: 65   },
      { id: '3', name: 'Leg Press',            sets: 3, reps: 15, weightKg: 120  },
      { id: '4', name: 'Walking Lunges',       sets: 3, reps: 20 },
      { id: '5', name: 'Calf Raises',          sets: 4, reps: 25 },
    ],
  },
  {
    id: '5',
    title: 'HIIT — Tabata',
    date: '2025-04-01',
    durationMinutes: 30,
    type: 'cardio',
    icon: '⚡',
    notes: '20s on / 10s off × 8 rounds. Brutal but effective.',
    exercises: [
      { id: '1', name: 'Burpees',          sets: 8, durationSeconds: 20 },
      { id: '2', name: 'Mountain Climbers', sets: 8, durationSeconds: 20 },
      { id: '3', name: 'Jump Squats',       sets: 8, durationSeconds: 20 },
      { id: '4', name: 'High Knees',        sets: 8, durationSeconds: 20 },
    ],
  },
  {
    id: '6',
    title: 'Evening Walk',
    date: '2025-03-31',
    durationMinutes: 40,
    type: 'cardio',
    icon: '🚶',
    notes: 'Recovery walk. Nice to unwind.',
    exercises: [
      { id: '1', name: 'Walking', durationSeconds: 2400 },
    ],
  },
];

export const mockStats = {
  currentStreak: 12,
  longestStreak: 21,
  tasksCompletedToday: 1,
  totalTasksToday: 6,
  goalsActive: 4,
  workoutsThisWeek: 3,
};
